"""Adiciona campos de quantidade de estoque, quantidade minima e status

Revision ID: 4c752ad8573a
Revises: ec0871a249b3
Create Date: 2026-05-06 12:03:21.928026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c752ad8573a'
down_revision: Union[str, Sequence[str], None] = 'ec0871a249b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock_quantity', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('min_stock', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'status')
    op.drop_column('products', 'min_stock')
    op.drop_column('products', 'stock_quantity')
    # ### end Alembic commands ###
