"""Recriando tabelas com novos campos

Revision ID: 6dad703cec57
Revises: ec0871a249b3
Create Date: 2026-05-06 12:42:53.721139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dad703cec57'
down_revision: Union[str, Sequence[str], None] = 'ec0871a249b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock_quantity', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('min_stock', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'status')
    op.drop_column('products', 'min_stock')
    op.drop_column('products', 'stock_quantity')
    # ### end Alembic commands ###
